[
  "XDG_CURRENT_DESKTOP,Hyprland"
  "XDG_SESSION_TYPE,wayland"
  "XDG_SESSION_DESKTOP,Hyprland"
  "QT_QPA_PLATFORM,wayland"
  "QT_QPA_PLATFORMTHEME,qt5ct"
  "QT_WAYLAND_DISABLE_WINDOWDECORATION,1"
  "QT_AUTO_SCREEN_SCALE_FACTOR,1"
  "MOZ_ENABLE_WAYLAND,1"
  "env = XCURSOR_SIZE = 26"
]
